profileId=dell_latitude_7410
modelContains=Latitude 7410
displayName=Dell Latitude 7410
validationStatus=draft
reference=Official Dell Latitude 7410 Setup and Specifications
port=left_tb3_top|Left Thunderbolt 3 #1|Left|USB-C|Thunderbolt 3 / Power Delivery / DisplayPort|true
port=left_tb3_bottom|Left Thunderbolt 3 #2|Left|USB-C|Thunderbolt 3 / Power Delivery / DisplayPort|true
port=left_hdmi|Left HDMI 2.0|Left|HDMI|HDMI 2.0 Video Output|true
port=right_usb_a1|Right USB 3.2 Gen 1 (PowerShare)|Right|USB-A|USB 3.2 Gen 1 with PowerShare|true
port=right_usb_a2|Right USB 3.2 Gen 1 #2|Right|USB-A|USB 3.2 Gen 1|true
port=right_microsd|Right MicroSD Card Slot|Right|MicroSD|MicroSD card reader 4.0|true
