profileId=dell_xps_15_9520
modelContains=XPS 15 9520
displayName=Dell XPS 15 9520
validationStatus=draft
reference=Official Dell XPS 15 9520 Setup and Specifications
port=left_tb4_top|Left Thunderbolt 4 #1|Left|USB-C|Thunderbolt 4 / USB4 / Power Delivery|true
port=left_tb4_bottom|Left Thunderbolt 4 #2|Left|USB-C|Thunderbolt 4 / USB4 / Power Delivery|true
port=right_usb_c|Right USB-C 3.2 Gen 2|Right|USB-C|USB 3.2 Gen 2 / DP / Power Delivery|true
port=right_sd|Right Full-size SD Card Slot|Right|SD|SD card reader v6.0|true
