profileId=hp_elitebook_840_g9
modelContains=EliteBook 840 G9
displayName=HP EliteBook 840 G9
validationStatus=draft
reference=HP QuickSpecs EliteBook 840 G9
port=left_hdmi|Left HDMI 2.0|Left|HDMI|HDMI 2.0 Video Output|true
port=left_usb_a|Left USB 3.2 Gen 1|Left|USB-A|USB 3.2 Gen 1|true
port=left_tb4_1|Left Thunderbolt 4 / USB4 #1|Left|USB-C|Thunderbolt 4 / USB4 / Power Delivery / DP 1.4|true
port=left_tb4_2|Left Thunderbolt 4 / USB4 #2|Left|USB-C|Thunderbolt 4 / USB4 / Power Delivery / DP 1.4|true
port=right_usb_a|Right USB 3.2 Gen 1 (Charging)|Right|USB-A|USB 3.2 Gen 1 Charging|true
