profileId=hp_probook_450_g8
modelContains=ProBook 450 G8
displayName=HP ProBook 450 G8
validationStatus=draft
reference=HP QuickSpecs ProBook 450 G8
port=left_rj45|Left RJ-45 Ethernet|Left|RJ45|Gigabit Ethernet LAN|true
port=left_usb_a|Left USB 3.2 Gen 1|Left|USB-A|USB 3.2 Gen 1|true
port=right_microsd|Right MicroSD Card Slot|Right|MicroSD|MicroSD Card Reader|true
port=right_usb_a1|Right USB 3.2 Gen 1 #1|Right|USB-A|USB 3.2 Gen 1|true
port=right_usb_a2|Right USB 3.2 Gen 1 #2|Right|USB-A|USB 3.2 Gen 1|true
port=right_hdmi|Right HDMI 1.4b|Right|HDMI|HDMI 1.4b Video Output|true
port=right_usbc|Right USB-C 3.2 Gen 2 (PD/DP)|Right|USB-C|USB-C 3.2 Gen 2 / Power Delivery / DP 1.4|true
