profileId=lenovo_thinkpad_e14_gen3
modelContains=E14 Gen 3
displayName=Lenovo ThinkPad E14 Gen 3
validationStatus=draft
reference=Lenovo PSREF ThinkPad E14 Gen 3
port=left_usbc|Left USB-C 3.2 Gen 1|Left|USB-C|USB-C / Power Delivery 3.0 / DP 1.2|true
port=left_usb_a|Left USB 3.2 Gen 1 (Always On)|Left|USB-A|USB 3.2 Gen 1 Always On|true
port=left_hdmi|Left HDMI 1.4b|Left|HDMI|HDMI 1.4b Video Output|true
port=right_rj45|Right RJ-45 Ethernet|Right|RJ45|Gigabit Ethernet LAN|true
port=right_usb_a|Right USB 2.0|Right|USB-A|USB 2.0|true
