profileId=lenovo_thinkpad_t14_gen2_intel
modelContains=T14 Gen 2
displayName=Lenovo ThinkPad T14 Gen 2 (Intel)
validationStatus=draft
reference=Lenovo PSREF ThinkPad T14 Gen 2 Intel
port=left_tb4_side|Left Thunderbolt 4 #1 (Side Dock)|Left|USB-C|Thunderbolt 4 / Power Delivery / DP 1.4a|true
port=left_tb4_main|Left Thunderbolt 4 #2|Left|USB-C|Thunderbolt 4 / Power Delivery / DP 1.4a|true
port=left_usb_a|Left USB 3.2 Gen 1|Left|USB-A|USB 3.2 Gen 1|true
port=left_hdmi|Left HDMI 2.0|Left|HDMI|HDMI 2.0|true
port=left_microsd|Left MicroSD Card Slot|Left|MicroSD|MicroSD card reader|true
port=right_rj45|Right RJ-45 Ethernet|Right|RJ45|Gigabit Ethernet LAN|true
port=right_usb_a|Right USB 3.2 Gen 1 (Always On)|Right|USB-A|USB 3.2 Gen 1 Always On|true
