#include "lap/report.h"
#include "lap/scoring.h"
#include "lap/functional.h"
#include "lap/port_power.h"
#include "lap/orchestrator.h"
#include "lap/runtime_validation.h"
#include "lap/chassis_profile.h"
#include <windows.h>
#include <shlobj.h>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iomanip>

namespace lap {
namespace {
std::wstring Html(std::wstring s){for(size_t p=0;(p=s.find(L"&",p))!=std::wstring::npos;p+=5)s.replace(p,1,L"&amp;");for(size_t p=0;(p=s.find(L"<",p))!=std::wstring::npos;p+=4)s.replace(p,1,L"&lt;");for(size_t p=0;(p=s.find(L">",p))!=std::wstring::npos;p+=4)s.replace(p,1,L"&gt;");for(size_t p=0;(p=s.find(L"\"",p))!=std::wstring::npos;p+=6)s.replace(p,1,L"&quot;");return s;}
std::wstring Json(const std::wstring&s){std::wstring o;for(wchar_t c:s){switch(c){case L'\"':o+=L"\\\"";break;case L'\\':o+=L"\\\\";break;case L'\b':o+=L"\\b";break;case L'\f':o+=L"\\f";break;case L'\n':o+=L"\\n";break;case L'\r':o+=L"\\r";break;case L'\t':o+=L"\\t";break;default:if(c<0x20){wchar_t b[7];swprintf_s(b,L"\\u%04x",(unsigned)c);o+=b;}else o+=c;}}return o;}
std::wstring Ts(){SYSTEMTIME t;GetLocalTime(&t);wchar_t b[64];swprintf_s(b,L"%04d%02d%02d_%02d%02d%02d",t.wYear,t.wMonth,t.wDay,t.wHour,t.wMinute,t.wSecond);return b;}
bool Writable(const std::filesystem::path&p){std::error_code ec;std::filesystem::create_directories(p,ec);if(ec)return false;auto test=p/L".write_test.tmp";std::ofstream f(test,std::ios::binary);if(!f)return false;f<<"ok";f.close();std::filesystem::remove(test,ec);return true;}
std::wstring F(double x,int n=1){if(x<0)return L"N/A";wchar_t b[64];swprintf_s(b,n==1?L"%.1f":L"%.2f",x);return b;}
std::wstring GiB(uint64_t b){return F((double)b/(1024.0*1024.0*1024.0),1);}
const wchar_t* ViDecision(const std::wstring&s){if(s==L"BUY")return L"CÓ THỂ MUA";if(s==L"BUY WITH NOTES")return L"CÓ THỂ MUA — CẦN LƯU Ý";if(s==L"REJECT")return L"KHÔNG NÊN MUA";return L"CHƯA ĐỦ DỮ LIỆU ĐỂ KẾT LUẬN";}
const wchar_t* ViStatus(const std::wstring&s){if(s==L"COMPLETE"||s==L"PASS"||s==L"HIGH")return L"ĐÃ KIỂM TRA ĐỦ";if(s==L"FAIL")return L"KHÔNG ĐẠT";if(s==L"WARNING")return L"CẦN LƯU Ý";if(s==L"PARTIAL")return L"CHƯA HOÀN TẤT";if(s==L"NOT TESTED"||s==L"NOT RUN")return L"CHƯA KIỂM TRA";return L"CHƯA XÁC ĐỊNH";}
const wchar_t* ViConfidence(Confidence c){return c==Confidence::High?L"Cao":(c==Confidence::Medium?L"Trung bình":L"Thấp");}
const wchar_t* ViTestVerdict(TestVerdict v){switch(v){case TestVerdict::Pass:return L"Đạt";case TestVerdict::Warning:return L"Cần lưu ý";case TestVerdict::Fail:return L"Không đạt";case TestVerdict::Cancelled:return L"Đã dừng";default:return L"Chưa kiểm tra";}}
bool WriteUtf8File(const std::filesystem::path&p,const std::wstring&text){if(text.size()>static_cast<size_t>(INT_MAX))return false;int n=WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,text.data(),static_cast<int>(text.size()),nullptr,0,nullptr,nullptr);if(n<=0)return false;std::string bytes(static_cast<size_t>(n),'\0');if(WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,text.data(),static_cast<int>(text.size()),bytes.data(),n,nullptr,nullptr)!=n)return false;std::ofstream out(p,std::ios::binary|std::ios::trunc);if(!out)return false;out.write(bytes.data(),static_cast<std::streamsize>(bytes.size()));out.flush();return out.good();}
}
std::wstring ResolveReportDirectory(const std::wstring& appDir,bool winPE){
 std::filesystem::path app(appDir);auto local=app/L"reports";
 if(Writable(local)&&(!winPE||towupper(app.root_name().wstring().empty()?L'?':app.root_name().wstring()[0])!=L'X'))return local.wstring();
 if(winPE){DWORD mask=GetLogicalDrives();for(wchar_t d=L'D';d<=L'Z';++d){if(!(mask&(1u<<(d-L'A')))||d==L'X')continue;std::wstring root;root+=d;root+=L":\\";UINT type=GetDriveTypeW(root.c_str());if(type==DRIVE_REMOVABLE||type==DRIVE_FIXED){std::filesystem::path p=root;p/=L"LapSureReports";if(Writable(p))return p.wstring();}}}
 wchar_t docs[MAX_PATH]{};if(SUCCEEDED(SHGetFolderPathW(nullptr,CSIDL_MYDOCUMENTS,nullptr,SHGFP_TYPE_CURRENT,docs))){std::filesystem::path p(docs);p/=L"LapSureReports";if(Writable(p))return p.wstring();}
 wchar_t temp[MAX_PATH]{};GetTempPathW(MAX_PATH,temp);std::filesystem::path p(temp);p/=L"LapSureReports";Writable(p);return p.wstring();
}
std::wstring SaveHtmlReport(const AuditReport&r,const std::wstring&dir){
 std::filesystem::create_directories(dir);auto p=std::filesystem::path(dir)/(L"audit_"+Ts()+L".html");std::wostringstream f;
 const auto overall=r.hardware.stress.decision.overall;const wchar_t*resultClass=overall==L"REJECT"?L"bad":((overall==L"BUY"||overall==L"BUY WITH NOTES")?L"ok":L"wait");
 f<<L"<!doctype html><html lang='vi'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Kết quả kiểm tra LapSure</title><style>:root{font-family:'Segoe UI',Arial,sans-serif;font-size:18px;line-height:1.55;color:#18202b;background:#f3f6fa}body{margin:0}.page{max-width:1180px;margin:auto;padding:24px}.hero,.card,details{background:white;border:1px solid #d8dee8;border-radius:14px;padding:20px;margin:14px 0;box-shadow:0 2px 8px #1e293b12}.hero h1{font-size:1.55rem;margin:0 0 8px}.result{border-left:10px solid;padding:24px}.result.ok{border-color:#16833b;background:#eefaf1}.result.wait{border-color:#bd7700;background:#fff8e8}.result.bad{border-color:#b42318;background:#fff1f0}.result .metric{font-size:2rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:14px}.metric{font-size:1.35rem;font-weight:750;margin:6px 0}.label{color:#536174}.status{font-weight:700}.ok-text{color:#116b32}.wait-text{color:#8a5300}.bad-text{color:#9f1c13}table{border-collapse:collapse;width:100%;background:white;font-size:.9rem}td,th{border:1px solid #d8dee8;padding:9px;vertical-align:top;text-align:left}th{background:#edf1f6}pre{white-space:pre-wrap;margin:0}summary{cursor:pointer;font-size:1.1rem;font-weight:700}.PASS,.GOOD{background:#e5f6e9}.FAIL{background:#ffe3e0}.WARNING{background:#fff3cf}.CHANGED{background:#ece8ff}@media(max-width:650px){.page{padding:12px}.metric{font-size:1.25rem}.result .metric{font-size:1.55rem}table{display:block;overflow-x:auto}}</style><body><main class='page'>";
 f<<L"<div class='hero'><h1>LapSure — Kết quả kiểm tra laptop</h1><b>"<<Html(r.model)<<L"</b> · Mã máy (Service Tag): "<<Html(r.serviceTag)<<L"<br><span class='label'>Môi trường kiểm tra: "<<Html(r.environment)<<L" · Cấu hình đối chiếu chính xác: "<<(r.factoryExact?L"Có":L"Chưa có")<<L"</span></div>";
 if(r.sellerClaim.provided)f<<L"<div class='card'><b>Cấu hình người bán cam kết</b><div>Model: "<<Html(r.sellerClaim.model)<<L" · CPU: "<<Html(r.sellerClaim.cpuContains)<<L" · RAM: "<<(r.sellerClaim.ramBytes/1073741824ULL)<<L" GB · Ổ lưu trữ: "<<(r.sellerClaim.storageBytes/1000000000ULL)<<L" GB · GPU: "<<Html(r.sellerClaim.gpuContains.empty()?L"Không ghi":r.sellerClaim.gpuContains)<<L"</div><div>Giá bán: "<<(r.sellerClaim.askingPriceVnd?std::to_wstring(r.sellerClaim.askingPriceVnd)+L" VNĐ":L"Chưa nhập")<<L" · Bảo hành: "<<r.sellerClaim.warrantyDays<<L" ngày</div></div>";
 f<<L"<section class='result "<<resultClass<<L"'><div class='label'>KẾT LUẬN HIỆN TẠI</div><div class='metric'>"<<ViDecision(overall)<<L"</div>";
 if(overall==L"REJECT")f<<L"<div>LapSure đã phát hiện lỗi nghiêm trọng. Không nên mua hoặc tiếp tục sử dụng trước khi kiểm tra và khắc phục.</div>";else if(overall==L"BUY"||overall==L"BUY WITH NOTES")f<<L"<div>Các phần kiểm tra bắt buộc đã hoàn tất. Hãy đọc các lưu ý bên dưới trước khi quyết định.</div>";else f<<L"<div>Chưa nên đưa ra quyết định mua. Hãy hoàn tất các mục còn thiếu được liệt kê ngay bên dưới.</div>";
 f<<L"<div>Độ tin cậy của kết quả: <b>"<<ViConfidence(r.hardware.stress.decision.confidence)<<L"</b></div></section>";
 f<<L"<div class='grid'>";
 f<<L"<div class='card'><b>Bộ xử lý (CPU)</b><div class='metric'>"<<Html(r.hardware.cpuName)<<L"</div><div>Luồng xử lý: "<<r.hardware.cpuThreads<<L"</div></div>";
 f<<L"<div class='card'><b>Bộ nhớ RAM</b><div class='metric'>"<<GiB(r.hardware.installedRamBytes)<<L" GB</div><div>Số thanh RAM: "<<r.hardware.memoryModules.size()<<L"</div></div>";
 f<<L"<div class='card'><b>Ổ lưu trữ</b><div class='metric'>"<<r.hardware.storage.size()<<L" ổ</div>";
 for(auto&d:r.hardware.storage)f<<L"<div>"<<Html(d.model)<<L" · "<<GiB(d.capacityBytes)<<L" GB · Tuổi thọ còn lại "<<(d.enduranceRemaining>=0?std::to_wstring(d.enduranceRemaining)+L"%":L"Chưa đọc được")<<L" · Nhiệt độ "<<(d.temperatureC>=0?std::to_wstring(d.temperatureC)+L"°C":L"Chưa đọc được")<<L"</div>";
 f<<L"</div>";
 f<<L"<div class='card'><b>Pin</b><div class='metric'>"<<F(r.hardware.battery.healthPercent)<<L"% sức khỏe</div><div>Dung lượng thiết kế "<<F(r.hardware.battery.designWh)<<L" Wh · Hiện còn "<<F(r.hardware.battery.fullChargeWh)<<L" Wh · Hao mòn "<<F(r.hardware.battery.wearPercent)<<L"%</div></div>";
 f<<L"<div class='card'><b>Đồ họa (GPU)</b><div class='metric'>"<<r.hardware.gpus.size()<<L" bộ xử lý</div>";for(auto&g:r.hardware.gpus)f<<L"<div>"<<Html(g.name)<<L" · Bộ nhớ đồ họa "<<(g.vramBytes?GiB(g.vramBytes)+L" GB":L"Chưa đọc được")<<L" · Nhiệt độ "<<(g.temperatureC>=0?F(g.temperatureC)+L"°C":L"Chưa đọc được")<<L"</div>";f<<L"</div>";
 f<<L"<div class='card'><b>Tiến độ kiểm tra</b><div class='metric'>"<<r.hardware.stress.orchestrator.percent<<L"%</div><div>Độ ổn định: "<<ViStatus(r.hardware.stress.decision.stability)<<L"</div><div>Nhiệt độ: "<<ViStatus(r.hardware.stress.decision.thermal)<<L"</div><div>Độ phủ: "<<ViStatus(r.hardware.stress.decision.coverage)<<L"</div></div>";
 f<<L"<div class='card'><b>Các phần cần hoàn tất</b><div>LapSure không tự suy đoán khi thiếu bằng chứng.</div>";
 for(const auto&x:BuildCoverageContract(r))f<<L"<div><span class='status'>"<<(x.status==L"COMPLETE"?L"✓ Đã đủ":L"! Chưa đủ")<<L"</span> — <b>"<<Html(x.name)<<L"</b>"<<(x.missingEvidence.empty()?L"":L": "+Html(x.missingEvidence))<<L"</div>";
 f<<L"</div>";
 f<<L"<details><summary>Thông tin kỹ thuật chi tiết</summary><div class='card'><b>Các bài kiểm tra độ ổn định</b><div class='metric'>Chế độ "<<Html(r.hardware.stress.mode)<<L"</div>";
 for(auto&s:r.hardware.stress.stages){f<<L"<div><b>"<<Html(s.name)<<L"</b> · "<<ViTestVerdict(s.verdict)<<L" · "<<s.elapsedSeconds<<L" giây · Lỗi phần cứng mới (WHEA): "<<s.newWhea;
   if(s.ram.bytesTested)f<<L" | RAM "<<F((double)s.ram.bytesTested/1073741824.0)<<L" GiB tested | mismatch "<<s.ram.mismatches;
   if(s.gpuVram.checkedGB>0||s.gpuVram.errors)f<<L" | VRAM "<<F(s.gpuVram.checkedGB)<<L" GB checked | errors "<<s.gpuVram.errors;
   if(s.telemetrySummary.sampleCount){f<<L" | CPU avg "<<F(s.telemetrySummary.avgCpuUtil)<<L"% | GPU max "<<F(s.telemetrySummary.maxGpuTempC)<<L"C";if(s.telemetrySummary.maxCpuPackageTempC>=0)f<<L" | CPU pkg max "<<F(s.telemetrySummary.maxCpuPackageTempC)<<L"C | CPU pkg max power "<<F(s.telemetrySummary.maxCpuPackagePowerW)<<L"W";}
   f<<L"</div>";
 }
 f<<L"</div>";
 f<<L"</div>";
 f<<L"<div class='card'><b>Kiểm tra chức năng</b><div class='metric'>"<<ViStatus(r.hardware.stress.functional.overall)<<L"</div><div>Đạt "<<r.hardware.stress.functional.passed<<L" · Không đạt "<<r.hardware.stress.functional.failed<<L" · Cần lưu ý "<<r.hardware.stress.functional.warning<<L" · Cần xác nhận "<<r.hardware.stress.functional.manualRequired<<L"</div>";
 for(auto&i:r.hardware.stress.functional.items)f<<L"<div>"<<Html(i.name)<<L" — "<<FunctionalStatusText(i.status)<<L" — "<<Html(i.detail)<<L"</div>";
 f<<L"</div>";
 f<<L"<div class='card'><b>Cổng kết nối và nguồn sạc</b><div class='metric'>"<<ViStatus(r.hardware.stress.portPower.overall)<<L"</div>";
 f<<L"<div>USB4 host router: "<<(r.hardware.stress.portPower.usb4HostRouterPresent?L"YES":L"NO/UNKNOWN")<<L" | USB4 device routers: "<<r.hardware.stress.portPower.usb4DeviceRouters<<L" | Thunderbolt matches: "<<r.hardware.stress.portPower.thunderboltDevices<<L"</div>";
 f<<L"<div>Power: "<<Html(r.hardware.stress.portPower.power.verdict)<<L" | Adapter watts: "<<(r.hardware.stress.portPower.power.adapterWatts<0?L"UNKNOWN":F(r.hardware.stress.portPower.power.adapterWatts))<<L"</div>";
 for(auto&port:r.hardware.stress.portPower.ports)f<<L"<div>"<<Html(port.portLabel)<<L" — "<<Html(port.verdict)<<L" — "<<Html(port.deviceDescription)<<L" — "<<Html(port.negotiatedSpeed)<<L"</div>";
 f<<L"</div>";
 f<<L"<div class='card'><b>Quy trình kiểm tra có hướng dẫn</b><div class='metric'>"<<r.hardware.stress.orchestrator.percent<<L"%</div><div>Bước tiếp theo: "<<Html(r.hardware.stress.orchestrator.nextAction)<<L"</div>";
 for(auto&s:r.hardware.stress.orchestrator.stages)f<<L"<div>"<<Html(s.title)<<L" — "<<StageStateText(s.state)<<L" — "<<s.completed<<L"/"<<s.total<<L" — "<<Html(s.subtitle)<<L"</div>";
 f<<L"</div>";
 f<<L"<div class='card'><b>Sơ đồ cổng theo đúng kiểu máy</b><div class='metric'>"<<Html(r.hardware.stress.chassisProfile.displayName.empty()?L"Chưa có cấu hình riêng":r.hardware.stress.chassisProfile.displayName)<<L"</div>";
 for(auto&port:r.hardware.stress.chassisProfile.ports)f<<L"<div>"<<Html(port.label)<<L" | "<<Html(port.side)<<L" | "<<Html(port.connector)<<L" | "<<Html(port.capability)<<L" | "<<(port.tested?Html(port.verdict):L"NOT TESTED")<<L"</div>";
 f<<L"</div>";
 f<<L"<div class='card'><b>Xác thực chương trình và báo cáo</b><div class='metric'>"<<ViStatus(r.hardware.stress.runtimeValidation.overall)<<L"</div><div>Bản dựng: "<<Html(r.hardware.stress.runtimeValidation.buildLabel)<<L" · Trình biên dịch: "<<Html(r.hardware.stress.runtimeValidation.compilerLabel)<<L" · Kiến trúc: "<<Html(r.hardware.stress.runtimeValidation.architecture)<<L"</div>";
 for(auto&x:r.hardware.stress.runtimeValidation.checks)f<<L"<div>"<<Html(x.name)<<L" — "<<ValidationStatusText(x.status)<<L" — "<<Html(x.detail)<<L"</div>";
 f<<L"</div>";
 f<<L"<h2>Toàn bộ bằng chứng kỹ thuật</h2><table><tr><th>Lĩnh vực</th><th>Nhóm</th><th>Hạng mục</th><th>Giá trị thực tế</th><th>Mức mong đợi</th><th>Trạng thái</th><th>Mức độ</th><th>Nguồn bằng chứng</th></tr>";
 for(auto&x:r.findings)f<<L"<tr><td>"<<ToString(x.dimension)<<L"</td><td>"<<Html(x.group)<<L"</td><td>"<<Html(x.name)<<L"</td><td><pre>"<<Html(x.value)<<L"</pre></td><td>"<<Html(x.expected)<<L"</td><td class='"<<ToString(x.state)<<L"'>"<<ToString(x.state)<<L"</td><td>"<<ToString(x.severity)<<L"</td><td>"<<Html(x.evidence)<<L"</td></tr>";
 f<<L"</table></details></main></body></html>";return WriteUtf8File(p,f.str())?p.wstring():L"";
}
std::wstring SaveJsonReport(const AuditReport&r,const std::wstring&dir){
 std::filesystem::create_directories(dir);auto p=std::filesystem::path(dir)/(L"audit_"+Ts()+L".json");std::wostringstream f;
 f<<L"{\n\"model\":\""<<Json(r.model)<<L"\",\"serviceTag\":\""<<Json(r.serviceTag)<<L"\",\"environment\":\""<<Json(r.environment)<<L"\",\"factoryExact\":"<<(r.factoryExact?L"true":L"false")<<L",\"genericMode\":"<<(r.genericMode?L"true":L"false")<<L",\"sellerClaim\":{\"provided\":"<<(r.sellerClaim.provided?L"true":L"false")<<L",\"model\":\""<<Json(r.sellerClaim.model)<<L"\",\"cpuContains\":\""<<Json(r.sellerClaim.cpuContains)<<L"\",\"ramBytes\":"<<r.sellerClaim.ramBytes<<L",\"gpuContains\":\""<<Json(r.sellerClaim.gpuContains)<<L"\",\"storageBytes\":"<<r.sellerClaim.storageBytes<<L",\"displayWidth\":"<<r.sellerClaim.displayWidth<<L",\"displayHeight\":"<<r.sellerClaim.displayHeight<<L",\"askingPriceVnd\":"<<r.sellerClaim.askingPriceVnd<<L",\"warrantyDays\":"<<r.sellerClaim.warrantyDays<<L"},\"coverageContract\":[";
 const auto coverage=BuildCoverageContract(r);for(size_t i=0;i<coverage.size();++i){const auto&x=coverage[i];f<<L"{\"id\":\""<<Json(x.id)<<L"\",\"name\":\""<<Json(x.name)<<L"\",\"status\":\""<<Json(x.status)<<L"\",\"required\":"<<(x.required?L"true":L"false")<<L",\"sources\":\""<<Json(x.sources)<<L"\",\"missingEvidence\":\""<<Json(x.missingEvidence)<<L"\"}"<<(i+1<coverage.size()?L",":L"");}f<<L"],\n";
 f<<L"\"hardware\":{\"cpu\":{\"name\":\""<<Json(r.hardware.cpuName)<<L"\",\"threads\":"<<r.hardware.cpuThreads<<L"},\"ram\":{\"totalBytes\":"<<r.hardware.installedRamBytes<<L",\"modules\":[";
 for(size_t i=0;i<r.hardware.memoryModules.size();++i){auto&m=r.hardware.memoryModules[i];f<<L"{\"capacityBytes\":"<<m.capacityBytes<<L",\"configuredSpeed\":"<<m.configuredSpeed<<L",\"ratedSpeed\":"<<m.ratedSpeed<<L",\"manufacturer\":\""<<Json(m.manufacturer)<<L"\",\"partNumber\":\""<<Json(m.partNumber)<<L"\",\"serial\":\""<<Json(m.serialNumber)<<L"\"}"<<(i+1<r.hardware.memoryModules.size()?L",":L"");}
 f<<L"]},\"battery\":{\"present\":"<<(r.hardware.battery.present?L"true":L"false")<<L",\"designWh\":"<<r.hardware.battery.designWh<<L",\"fullWh\":"<<r.hardware.battery.fullChargeWh<<L",\"healthPercent\":"<<r.hardware.battery.healthPercent<<L",\"wearPercent\":"<<r.hardware.battery.wearPercent<<L",\"cycleCount\":"<<r.hardware.battery.cycleCount<<L"},\"storage\":[";
 for(size_t i=0;i<r.hardware.storage.size();++i){auto&d=r.hardware.storage[i];f<<L"{\"device\":\""<<Json(d.devicePath)<<L"\",\"model\":\""<<Json(d.model)<<L"\",\"serial\":\""<<Json(d.serialNumber)<<L"\",\"firmware\":\""<<Json(d.firmware)<<L"\",\"capacityBytes\":"<<d.capacityBytes<<L",\"reliabilityReadable\":"<<(d.reliabilityReadable?L"true":L"false")<<L",\"reliabilityHealthy\":"<<(d.reliabilityHealthy?L"true":L"false")<<L",\"reliabilityProvider\":\""<<Json(d.reliabilityProvider)<<L"\",\"healthStatus\":\""<<Json(d.healthStatus)<<L"\",\"operationalStatus\":\""<<Json(d.operationalStatus)<<L"\",\"smartReadable\":"<<(d.smartReadable?L"true":L"false")<<L",\"smartPassed\":"<<(d.smartPassed?L"true":L"false")<<L",\"percentageUsed\":"<<d.percentageUsed<<L",\"enduranceRemaining\":"<<d.enduranceRemaining<<L",\"mediaErrors\":"<<d.mediaErrors<<L",\"readErrorsUncorrected\":"<<d.readErrorsUncorrected<<L",\"writeErrorsUncorrected\":"<<d.writeErrorsUncorrected<<L",\"criticalWarning\":"<<d.criticalWarning<<L",\"powerOnHours\":"<<d.powerOnHours<<L",\"powerCycles\":"<<d.powerCycles<<L",\"unsafeShutdowns\":"<<d.unsafeShutdowns<<L",\"dataReadTB\":"<<d.approxDataReadTB<<L",\"dataWrittenTB\":"<<d.approxDataWrittenTB<<L",\"temperatureC\":"<<d.temperatureC<<L"}"<<(i+1<r.hardware.storage.size()?L",":L"");}
 f<<L"],\"gpus\":[";
 for(size_t i=0;i<r.hardware.gpus.size();++i){auto&g=r.hardware.gpus[i];f<<L"{\"name\":\""<<Json(g.name)<<L"\",\"vramBytes\":"<<g.vramBytes<<L",\"driver\":\""<<Json(g.driver)<<L"\",\"vbios\":\""<<Json(g.vbios)<<L"\",\"temperatureC\":"<<g.temperatureC<<L",\"powerW\":"<<g.powerW<<L"}"<<(i+1<r.hardware.gpus.size()?L",":L"");}
 f<<L"],\"stress\":{\"mode\":\""<<Json(r.hardware.stress.mode)<<L"\",\"completed\":"<<(r.hardware.stress.completed?L"true":L"false")<<L",\"decision\":{\"overall\":\""<<Json(r.hardware.stress.decision.overall)<<L"\",\"stability\":\""<<Json(r.hardware.stress.decision.stability)<<L"\",\"thermal\":\""<<Json(r.hardware.stress.decision.thermal)<<L"\",\"performance\":\""<<Json(r.hardware.stress.decision.performance)<<L"\",\"coverage\":\""<<Json(r.hardware.stress.decision.coverage)<<L"\",\"confidence\":\""<<ConfidenceText(r.hardware.stress.decision.confidence)<<L"\",\"reasons\":[";for(size_t i=0;i<r.hardware.stress.decision.reasons.size();++i)f<<L"\""<<Json(r.hardware.stress.decision.reasons[i])<<L"\""<<(i+1<r.hardware.stress.decision.reasons.size()?L",":L"");f<<L"]},\"stages\":[";
 for(size_t i=0;i<r.hardware.stress.stages.size();++i){auto&s=r.hardware.stress.stages[i];f<<L"{\"name\":\""<<Json(s.name)<<L"\",\"verdict\":\""<<VerdictText(s.verdict)<<L"\",\"elapsedSeconds\":"<<s.elapsedSeconds<<L",\"newWhea\":"<<s.newWhea<<L",\"newDisk\":"<<s.newDisk<<L",\"newNvme\":"<<s.newNvme<<L",\"newDisplay\":"<<s.newDisplay<<L",\"newBugCheck\":"<<s.newBugCheck<<L",\"telemetrySamples\":"<<s.telemetrySummary.sampleCount<<L",\"avgCpuUtil\":"<<s.telemetrySummary.avgCpuUtil<<L",\"maxGpuTempC\":"<<s.telemetrySummary.maxGpuTempC<<L",\"ramMismatches\":"<<s.ram.mismatches<<L",\"vramErrors\":"<<s.gpuVram.errors<<L"}"<<(i+1<r.hardware.stress.stages.size()?L",":L"");}
 f<<L"]},\"functional\":{\"overall\":\""<<Json(r.hardware.stress.functional.overall)<<L"\",\"passed\":"<<r.hardware.stress.functional.passed<<L",\"failed\":"<<r.hardware.stress.functional.failed<<L",\"warning\":"<<r.hardware.stress.functional.warning<<L",\"notTested\":"<<r.hardware.stress.functional.notTested<<L",\"manualRequired\":"<<r.hardware.stress.functional.manualRequired<<L",\"items\":[";
 for(size_t i=0;i<r.hardware.stress.functional.items.size();++i){auto&x=r.hardware.stress.functional.items[i];f<<L"{\"id\":\""<<Json(x.id)<<L"\",\"name\":\""<<Json(x.name)<<L"\",\"status\":\""<<FunctionalStatusText(x.status)<<L"\",\"detail\":\""<<Json(x.detail)<<L"\",\"evidence\":\""<<Json(x.evidence)<<L"\"}"<<(i+1<r.hardware.stress.functional.items.size()?L",":L"");}
 f<<L"]},\"portPower\":{\"overall\":\""<<Json(r.hardware.stress.portPower.overall)<<L"\",\"ports\":[";for(size_t i=0;i<r.hardware.stress.portPower.ports.size();++i){auto&x=r.hardware.stress.portPower.ports[i];f<<L"{\"label\":\""<<Json(x.portLabel)<<L"\",\"verdict\":\""<<Json(x.verdict)<<L"\",\"instanceId\":\""<<Json(x.instanceId)<<L"\",\"locationPath\":\""<<Json(x.locationPath)<<L"\"}"<<(i+1<r.hardware.stress.portPower.ports.size()?L",":L"");}f<<L"]},\"runtimeValidation\":{\"overall\":\""<<Json(r.hardware.stress.runtimeValidation.overall)<<L"\",\"failed\":"<<r.hardware.stress.runtimeValidation.failed<<L",\"warning\":"<<r.hardware.stress.runtimeValidation.warning<<L"},\"chassisProfile\":{\"id\":\""<<Json(r.hardware.stress.chassisProfile.profileId)<<L"\",\"requiredRemaining\":"<<RequiredPortsRemaining(r.hardware.stress.chassisProfile)<<L"},\"orchestrator\":{\"overall\":\""<<Json(r.hardware.stress.orchestrator.overall)<<L"\",\"percent\":"<<r.hardware.stress.orchestrator.percent<<L"}},\n\"findings\":[\n";
 for(size_t i=0;i<r.findings.size();++i){auto&x=r.findings[i];f<<L"{\"dimension\":\""<<ToString(x.dimension)<<L"\",\"group\":\""<<Json(x.group)<<L"\",\"name\":\""<<Json(x.name)<<L"\",\"value\":\""<<Json(x.value)<<L"\",\"expected\":\""<<Json(x.expected)<<L"\",\"state\":\""<<ToString(x.state)<<L"\",\"severity\":\""<<ToString(x.severity)<<L"\",\"evidence\":\""<<Json(x.evidence)<<L"\"}"<<(i+1<r.findings.size()?L",":L"")<<L"\n";}
 f<<L"]}\n";return WriteUtf8File(p,f.str())?p.wstring():L"";
}
} // namespace lap
