#include "lap/stress.h"
#include "lap/process.h"
#include "lap/telemetry.h"
#include "lap/trust.h"
#include "lap/journal.h"
#include "lap/scoring.h"
#include "lap/baseline.h"
#include <windows.h>
#include <thread>
#include <vector>
#include <chrono>
#include <sstream>
#include <algorithm>
#include <filesystem>
#include <mutex>
#include <cstring>
#include <cmath>
#include <regex>

namespace lap {
bool HasNewEventRecord(long long beforeRecordId,long long afterRecordId){return afterRecordId>beforeRecordId;}
namespace {
void Add(AuditReport&r,std::wstring g,std::wstring n,std::wstring v,std::wstring e,State st,Severity sv,Dimension d,std::wstring ev=L""){r.findings.push_back({std::move(g),std::move(n),std::move(v),std::move(e),st,sv,std::move(ev),d});}
std::wstring Q(const std::wstring&s){return L"\""+s+L"\"";}
std::wstring SessionId(){SYSTEMTIME t{};GetLocalTime(&t);wchar_t b[64];swprintf_s(b,L"%04d%02d%02d_%02d%02d%02d_%lu",t.wYear,t.wMonth,t.wDay,t.wHour,t.wMinute,t.wSecond,GetCurrentProcessId());return b;}
EventForensicSummary SnapshotEvents(const Capabilities& caps,const std::atomic_bool* cancel){EventForensicSummary x{};if(!caps.powershell)return x;auto command=L"powershell.exe -NoProfile -NonInteractive -Command \"$s=(Get-Date).AddMinutes(-10);$ps=@('WHEA-Logger','Disk','stornvme','Display','BugCheck');foreach($n in $ps){try{$e=@(Get-WinEvent -FilterHashtable @{LogName='System';ProviderName=$n;StartTime=$s} -ErrorAction Stop);$c=if($e.Count){($e|Measure-Object -Property RecordId -Maximum).Maximum}else{0}}catch{$c=-1};'{0}|{1}' -f $n,$c}\"";auto p=RunProcessCapture(command,20000,cancel);if(!p.launched||p.timedOut||p.cancelled)return x;bool any=false;for(auto&line:SplitLines(p.output)){auto q=Split(line,L'|');if(q.size()<2)continue;auto n=ParseI64(q[1],-1);if(n<0)continue;any=true;if(q[0]==L"WHEA-Logger")x.whea=n;else if(q[0]==L"Disk")x.disk=n;else if(q[0]==L"stornvme")x.stornvme=n;else if(q[0]==L"Display")x.display=n;else if(q[0]==L"BugCheck")x.bugCheck=n;}x.querySucceeded=any;return x;}
long long Delta(long long a,long long b){return HasNewEventRecord(a,b)?1:0;}
StressStageResult Finish(std::wstring name,unsigned planned,unsigned elapsed,const EventForensicSummary&a,const EventForensicSummary&b,bool cancelled,bool timedOut,std::wstring evidence){StressStageResult s{};s.name=std::move(name);s.plannedSeconds=planned;s.elapsedSeconds=elapsed;s.cancelled=cancelled;s.timedOut=timedOut;s.evidence=std::move(evidence);s.newWhea=Delta(a.whea,b.whea);s.newDisk=Delta(a.disk,b.disk);s.newNvme=Delta(a.stornvme,b.stornvme);s.newDisplay=Delta(a.display,b.display);s.newBugCheck=Delta(a.bugCheck,b.bugCheck);if(cancelled)s.verdict=TestVerdict::Cancelled;else if(!b.querySucceeded){s.verdict=TestVerdict::NotTested;s.evidence+=L" Event Log attribution unavailable.";}else if(timedOut||s.newWhea||s.newDisk||s.newNvme||s.newDisplay||s.newBugCheck)s.verdict=TestVerdict::Fail;else s.verdict=TestVerdict::Pass;return s;}
State ToState(TestVerdict v){switch(v){case TestVerdict::Pass:return State::Pass;case TestVerdict::Warning:return State::Warning;case TestVerdict::Fail:return State::Fail;default:return State::NotTested;}}
std::wstring Verdict(TestVerdict v){switch(v){case TestVerdict::Pass:return L"PASS";case TestVerdict::Warning:return L"WARNING";case TestVerdict::Fail:return L"FAIL";case TestVerdict::Cancelled:return L"CANCELLED";default:return L"NOT TESTED";}}

StressStageResult CpuStage(const Capabilities&caps,const std::wstring&appDir,const std::wstring&sessionId,unsigned seconds,const std::atomic_bool*cancel){WriteStressJournal(appDir,sessionId,L"CPU sustained load",L"RUNNING");auto before=SnapshotEvents(caps,cancel);auto start=std::chrono::steady_clock::now();SYSTEM_INFO si{};GetSystemInfo(&si);unsigned n=std::max<DWORD>(1,si.dwNumberOfProcessors);std::atomic_bool stop{false};std::vector<std::thread> threads;for(unsigned i=0;i<n;i++)threads.emplace_back([&]{volatile double x=1.000001;while(!stop.load(std::memory_order_relaxed)){for(int k=0;k<20000;k++)x=x*1.0000001+0.0000001;if(cancel&&cancel->load())break;}});bool cancelled=false;std::vector<TelemetrySample> samples;for(unsigned i=0;i<seconds*10;i++){if(cancel&&cancel->load()){cancelled=true;break;}Sleep(100);if(i%10==9)samples.push_back(SampleTelemetry((i+1)/10,caps,appDir,cancel));}stop=true;for(auto&t:threads)t.join();auto after=SnapshotEvents(caps,cancel);auto elapsed=(unsigned)std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now()-start).count();auto result=Finish(L"CPU sustained load",seconds,elapsed,before,after,cancelled,false,L"Built-in bounded all-logical-processor floating-point load; event delta + telemetry captured.");result.telemetry=std::move(samples);WriteStressJournal(appDir,sessionId,L"CPU sustained load",cancelled?L"CANCELLED":L"COMPLETED");return result;}

StressStageResult RamOnlineStage(const Capabilities&caps,const std::wstring&appDir,const std::wstring&sessionId,unsigned seconds,const std::atomic_bool*cancel){StressStageResult out{};out.name=L"RAM online integrity";out.plannedSeconds=seconds;WriteStressJournal(appDir,sessionId,out.name,L"RUNNING");auto before=SnapshotEvents(caps,cancel);auto start=std::chrono::steady_clock::now();MEMORYSTATUSEX ms{sizeof(ms)};GlobalMemoryStatusEx(&ms);uint64_t target=(uint64_t)(ms.ullAvailPhys*0.50);const uint64_t cap=8ull*1024ull*1024ull*1024ull;if(target>cap)target=cap;const size_t chunk=64ull*1024ull*1024ull;std::vector<unsigned char*> blocks;uint64_t allocated=0;while(allocated+chunk<=target){auto*p=(unsigned char*)VirtualAlloc(nullptr,chunk,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE);if(!p)break;blocks.push_back(p);allocated+=chunk;}out.ram.bytesAllocated=allocated;if(allocated<256ull*1024ull*1024ull){for(auto*p:blocks)VirtualFree(p,0,MEM_RELEASE);out.verdict=TestVerdict::NotTested;out.evidence=L"Insufficient free memory for meaningful online RAM coverage.";WriteStressJournal(appDir,sessionId,out.name,L"NOT_TESTED");return out;}const unsigned char patterns[]={0x00,0xFF,0xAA,0x55};bool cancelled=false;uint64_t mismatches=0,tested=0;unsigned passes=0;auto deadline=start+std::chrono::seconds(seconds);while(std::chrono::steady_clock::now()<deadline&&!cancelled){for(unsigned char pat:patterns){for(auto*p:blocks){if(cancel&&cancel->load()){cancelled=true;break;}std::memset(p,pat,chunk);for(size_t i=0;i<chunk;i++){if((i&0xfffff)==0&&cancel&&cancel->load()){cancelled=true;break;}if(p[i]!=pat)mismatches++;tested++;}if(cancelled)break;}if(cancelled||std::chrono::steady_clock::now()>=deadline)break;}if(!cancelled)++passes;}for(auto*p:blocks)VirtualFree(p,0,MEM_RELEASE);auto after=SnapshotEvents(caps,cancel);auto elapsed=(unsigned)std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now()-start).count();out=Finish(out.name,seconds,elapsed,before,after,cancelled,false,L"Built-in ONLINE partial-coverage RAM pattern test with byte-for-byte verification. It does not replace preboot MemTest86+.");out.ram.bytesAllocated=allocated;out.ram.bytesTested=tested;out.ram.mismatches=mismatches;out.ram.passes=passes;if(mismatches>0)out.verdict=TestVerdict::Fail;else if(!cancelled&&out.verdict==TestVerdict::Pass)out.verdict=TestVerdict::Warning;WriteStressJournal(appDir,sessionId,out.name,cancelled?L"CANCELLED":mismatches?L"FAILED":L"COMPLETED_PARTIAL");return out;}

GpuVramMetrics ParseMemtestVulkanOutputImpl(const std::wstring&text){GpuVramMetrics m{};std::wregex errorRx(L"(?:total errors|errors?)\\s*[:=]\\s*([0-9]+)",std::regex_constants::icase);std::wregex perfRx(L"written:\\s*([0-9.]+)GB.*?(?:checked|read):\\s*([0-9.]+)GB.*?([0-9.]+)GB/sec",std::regex_constants::icase);for(const auto&line:SplitLines(text)){std::wsmatch x;if(std::regex_search(line,x,errorRx))m.errors=std::max<uint64_t>(m.errors,std::stoull(x[1].str()));if(std::regex_search(line,x,perfRx)){m.writtenGB=ParseDouble(x[1].str(),m.writtenGB);m.checkedGB=ParseDouble(x[2].str(),m.checkedGB);m.throughputGBs=ParseDouble(x[3].str(),m.throughputGBs);}}m.standardFiveMinutePassed=text.find(L"Standard 5-minute test PASSed")!=std::wstring::npos&&m.errors==0&&m.checkedGB>0;return m;}
StressStageResult MemtestVulkanStage(const Capabilities&caps,const std::wstring&appDir,const std::wstring&sessionId,unsigned seconds,const std::atomic_bool*cancel){StressStageResult out{};out.name=L"GPU / VRAM integrity";out.plannedSeconds=seconds;auto trust=VerifyEngine(appDir,L"tools\\gpu\\memtest_vulkan.exe",L"memtest_vulkan");if(!trust.fileExists||!trust.manifestEntry||!trust.hashMatches){out.verdict=TestVerdict::NotTested;out.evidence=L"memtest_vulkan trust gate failed: "+trust.reason+L" SHA256="+trust.sha256;return out;}auto exe=(std::filesystem::path(appDir)/L"tools\\gpu\\memtest_vulkan.exe").wstring();WriteStressJournal(appDir,sessionId,out.name,L"RUNNING");auto before=SnapshotEvents(caps,cancel);auto start=std::chrono::steady_clock::now();auto p=RunProcessCapture(Q(exe),seconds*1000+30000,cancel);auto after=SnapshotEvents(caps,cancel);auto elapsed=(unsigned)std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now()-start).count();out=Finish(out.name,seconds,elapsed,before,after,cancel&&cancel->load(),p.timedOut,L"Trusted memtest_vulkan SHA256="+trust.sha256+L"; exit="+std::to_wstring(p.exitCode));out.gpuVram=ParseMemtestVulkanOutputImpl(p.output);if(!p.launched)out.verdict=TestVerdict::NotTested;else if(p.timedOut||p.exitCode!=0||out.gpuVram.errors>0)out.verdict=TestVerdict::Fail;else if(out.gpuVram.standardFiveMinutePassed&&out.newWhea==0&&out.newDisplay==0&&out.newBugCheck==0)out.verdict=TestVerdict::Pass;else out.verdict=TestVerdict::Warning;out.evidence+=L"; VRAM errors="+std::to_wstring(out.gpuVram.errors)+L"; standard5min="+(out.gpuVram.standardFiveMinutePassed?L"yes":L"no");WriteStressJournal(appDir,sessionId,out.name,out.verdict==TestVerdict::Pass?L"COMPLETED":out.verdict==TestVerdict::Fail?L"FAILED":L"INCOMPLETE");return out;}
}

GpuVramMetrics ParseMemtestVulkanOutput(const std::wstring&text){return ParseMemtestVulkanOutputImpl(text);}
StressPlan MakeStressPlan(const std::wstring&mode){StressPlan p{};p.mode=mode;if(mode==L"Standard"){p.cpuSeconds=120;p.ramSeconds=180;p.gpuSeconds=120;}else if(mode==L"Deep"){p.cpuSeconds=600;p.ramSeconds=900;p.gpuSeconds=600;}else {p.mode=L"Quick";p.cpuSeconds=30;p.ramSeconds=30;p.gpuSeconds=30;}return p;}
void RunStressSession(AuditReport&r,const Capabilities&caps,const std::wstring&appDir,const StressPlan&plan,const std::atomic_bool*cancel){auto&ss=r.hardware.stress;ss.mode=plan.mode;ss.stages.clear();ss.completed=false;ss.journalPath=StressJournalPath(appDir);std::wstring oldEvidence;ss.previousInterruptedSessionDetected=DetectInterruptedStressJournal(appDir,oldEvidence);if(ss.previousInterruptedSessionDetected)Add(r,L"Stability",L"Previous interrupted stress session",oldEvidence,L"No abandoned RUNNING journal",State::Warning,Severity::Critical,Dimension::Health,L"Crash/reboot/interruption evidence.");ss.sessionId=SessionId();const auto& sessionId=ss.sessionId;WriteStressJournal(appDir,sessionId,L"SESSION",L"RUNNING");auto a=SnapshotEvents(caps,cancel);ss.wheaBefore=a.whea;ss.diskBefore=a.disk;ss.nvmeBefore=a.stornvme;ss.displayBefore=a.display;ss.bugCheckBefore=a.bugCheck;ss.stages.push_back(CpuStage(caps,appDir,sessionId,plan.cpuSeconds,cancel));if(!(cancel&&cancel->load()))ss.stages.push_back(RamOnlineStage(caps,appDir,sessionId,plan.ramSeconds,cancel));if(!(cancel&&cancel->load()))ss.stages.push_back(MemtestVulkanStage(caps,appDir,sessionId,plan.gpuSeconds,cancel));auto b=SnapshotEvents(caps,cancel);ss.wheaAfter=b.whea;ss.diskAfter=b.disk;ss.nvmeAfter=b.stornvme;ss.displayAfter=b.display;ss.bugCheckAfter=b.bugCheck;ss.completed=!(cancel&&cancel->load());if(ss.completed)CompleteStressJournal(appDir);ss.cpuBenchmark=RunCpuMicroBenchmark(r.hardware.cpuName,appDir,cancel);for(auto&s:ss.stages){AssessStressStage(s);std::wstringstream v;v<<Verdict(s.verdict)<<L" | "<<s.elapsedSeconds<<L"/"<<s.plannedSeconds<<L"s | new WHEA "<<s.newWhea<<L" | Disk "<<s.newDisk<<L" | NVMe "<<s.newNvme<<L" | Display "<<s.newDisplay<<L" | BugCheck "<<s.newBugCheck;Add(r,L"Stability",s.name,v.str(),L"No new hardware errors",ToState(s.verdict),Severity::Critical,Dimension::Health,s.evidence);}ss.decision=BuildAuditDecision(r);}
}
